INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (1, '트림', '모델', '르블랑', '20인치 알로이 휠, 서라운드 모니터, 클러스터(12.3인치 컬러 LCD)', 41980000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/model/le_blanc', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (2, '트림', '모델', 'Exclusive', '12.3인치 내비게이션, 내비게이션 기반 스마트 크루즈 컨트롤, 베젤리스 인사이드 미러', 38960000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/model/exclusice.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (3, '트림', '모델', 'Prestige', '2열 수동식 도어 버튼, 스마트 자세제어, 전후석 통합 터치 공조 컨트롤', 46240000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/model/prestige.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (4, '트림', '모델', 'Calligraphy', 'KRELL 프리미엄 사운드, 원격 스마트 주차 보조, 캘리그래피 전용 디자인', 51060000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/model/calligraphy.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (5, '트림', '엔진', '디젤 2.2', '높은 토크로 파워풀한 드라이빙이 가능하며, 차급대비 연비 효율이 우수합니다
최고출력 202/3,800PS/rpm
최대토크 45.0/1,750~2,750kgf-m/rpm', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/power/diesel.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (6, '트림', '엔진', '가솔린 3.8', '고마력의 우수한 가속 성능을 확보하여, 넉넉하고 안정감 있는 주행이 가능합니다
엔진의 진동이 적어 편안하고 조용한 드라이빙 감성을 제공합니다
최고출력 295/6,000PS/rpm
최대토크 36.2/5,200kgf-m/rpm', 1480000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/power/gasoline.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (7, '트림', '바디타입', '7인승', '기존 8인승 시트(1열 2명, 2열 3명, 3열 3명)에서 2열 가운데 시트를 없애 2열 탑승객의 편의는 물론, 3열 탑승객의 승하차가 편리합니다', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/body_type/seven.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (8, '트림', '바디타입', '8인승', '1열 2명, 2열 3명, 3열 3명이 탑승할 수 있는 구조로, 많은 인원이 탑승할 수 있도록 배려하였습니다', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/body_type/eight.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (9, '트림', '구동방식', '2WD', '엔진에서 전달되는 동력이 전/후륜 바퀴 중 한쪽으로만 전달되어 차량을 움직이는 방식입니다
차체가 가벼워 연료 효율이 높습니다', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/driving_method/2wd.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (10, '트림', '구동방식', '4WD', '전자식 상시 4륜 구동 시스템 입니다
도로의 상황이나 주행 환경에 맞춰 전후륜 구동력을 자동배분하여 주행 안전성을 높여줍니다', 2370000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/driving_method/4wd.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (11, '색상', '외장색상', '어비스블랙펄', null, null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external_color/black.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (12, '색상', '외장색상', '쉬머링 실버 메탈릭', null, null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external_color/silver.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (13, '색상', '외장색상', '문라이프 블루 펄', null, null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external_color/blue.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (14, '색상', '외장색상', '가이아 브라운 펄', null, null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external_color/brown.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (15, '색상', '외장색상', '그라파이트 그레이 메탈릭', null, null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external_color/gray.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (16, '색상', '외장색상', '크리미 화이트 펄', null, 100000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external_color/white.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (17, '색상', '내장색상', '퀄팅천연(블랙)', null, null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/internal_color/black.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (18, '색상', '내장색상', '쿨그레이', null, null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/internal_color/gray.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (19, '색상', '내장색상-이미지', '퀄팅천연(블랙) 내장 이미지', null, null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/internal_color/balck_internal.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (20, '색상', '내장색상-이미지', '쿨그레이 내장 이미지', null, null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/internal_color/gray_internal.png', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (21, '기본 포함 품목', '파워트레인/성능', '8단 자동변속기', '전달 효율 증대로 전 엔진 동급 최고의 연비를 구현함은 물론, 최적의 변속 성능으로 드라이빙 감성까지 향상시켜줍니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/power/transmission.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (22, '기본 포함 품목', '파워트레인/성능', 'ISG 시스템', '신호 대기 상황이거나 정차 중일 때 차의 엔진을 일시 정지하여 연비를 향상시키고, 배출가스 발생을 억제하는 시스템입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/power/ISG.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (23, '기본 포함 품목', '파워트레인/성능', '통합주행모드', 'COMFORT, ECO, SPORT, SMART 4가지 드라이브 모드를 지원하여 운전자의 니즈에 따른 다양한 주행 모드를 선택할 수 있습니다. 각 주행모드의 상태는 클러스터와 AVN을 통해 확인 가능합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/power/driving_mode.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (24, '기본 포함 품목', '파워트레인/성능', '랙구동형 전동식 파워스티어링(R-MD', '조향 시 운전자의 힘을 유압대신 모터가 바퀴로 전달하는 기술로 모터가 차량 하체에 장착되어 타이어를 제어합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/power/power_steering.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (25, '기본 포함 품목', '파워트레인/성능', '전자식 변속버튼', '전자식 변속 버튼을 적용하여 조작 편의성을 높이는 동시에 하이테크적인 이미지를 연출했습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/power/shift_button.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (26, '기본 포함 품목', '지능형 안전기술', '하이빔 보조', '마주오는 차량 또는 앞 차량의 램프 및 주변 밝기 상태를 감지하여 전조등을 자동으로 상향 또는 하향으로 전환합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/hba.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (27, '기본 포함 품목', '지능형 안전기술', '진동 경고 스티어링 휠', '전방 차량과의 충돌/차량의 차선 이탈/후측방 충돌 위험 시, 운전자 주의 경고 시 스티어링에 진동을 주어 경고합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/vibsteeringwheel.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (28, '기본 포함 품목', '지능형 안전기술', '스마트 크루즈 컨트롤(스탑앤고 기능 ', '전방의 차량을 감지하여 스스로 가속과 감속을 하며 차량의 속도를 일정하게 유지 시켜주고, 차량 정체로 앞차 정차 시 정지하고 전방 차량 출발 시 다시 거리를 유지하며 주행하는 기능입니다.
※ 단, 자동 정차 시간이 3초 초과 시, 별도 조작으로 출발 가능', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/scc.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (29, '기본 포함 품목', '지능형 안전기술', '내비게이션 기반 스마트 크루즈 컨트롤', '스마트 크루즈 작동 중 고속도로/도시고속도로/자동차전용 도로 내 안전구간 진입 시, 감속 제어를 통해 주행 편의 제공합니다. 또한 곡선 구간 진입 시, 감속 제어를 통해 주행 편의를 제공합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/ncss.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (30, '기본 포함 품목', '지능형 안전기술', '고속도로 주행보조', '고속도로 본선 주행 시 전방 차량과의 거리, 차선 정보, 내비게이션 정보를 이용하여 차량 속도를 제어는 물론 차로 유지를 보조해줍니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/hba.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (31, '기본 포함 품목', '지능형 안전기술', '차로 유지 보조', '전방 카메라를 이용하여 차선을 인식하고 차로의 중앙으로 주행할 수 있도록 조향을 보조합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/lfa.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (32, '기본 포함 품목', '지능형 안전기술', '전방 충돌방지 보조(차량/보행자/자전', '전방 카메라와 전방 레이더의 신호를 종합적으로 판단하여 전방 차량, 보행자, 자전거 탑승자와 충돌 위험 상황이 감지될 경우 운전자에게 이를 경고하고, 필요 시 브레이크 작동을 도와줍니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/fca.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (33, '기본 포함 품목', '지능형 안전기술', '차로 이찰방지 보조', '전방 카메라로 주행 차로를 실시간으로 감지하여 차량이 차로를 이탈하려 할 경우, 클러스터에 경고하고 스티어링 휠을 제어하여 안전하게 주행 차로를 유지하도록 보조합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/lka.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (34, '기본 포함 품목', '지능형 안전기술', '운전자 주의 경고', '차량이 스스로 운전자의 주행 패턴과 차로 내 차량 위치 등을 종합적으로 분석하여 주의 운전이 필요하다고 판단되면, 팝업메시지와 경고음을 통해 운전자 휴식을 유도합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/daw.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (35, '기본 포함 품목', '지능형 안전기술', '후측방 충돌 경고(주행)', '차로 변경을 위하여 방향지시등 스위치 조작 시, 후측방 충돌 위험이 감지되면 경고를 해줍니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/bcw.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (36, '기본 포함 품목', '지능형 안전기술', '후측방 충돌방지 보조(전진 출차)', '평행 주차상태에서 전진 출차 중, 후측방 차량과 충돌 위험이 감지되면 자동으로 제동을 도와줍니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/bca.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (37, '기본 포함 품목', '지능형 안전기술', '안전 하차 보조', '정차 후 탑승자가 차에서 내리려고 도어를 열 때, 후측방에서 접근하는 차량이 감지되면 경고를 해줍니다. 또한 전자식 차일드 락이 작동하여 문이 열리지 않도록 도와줍니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/sea.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (38, '기본 포함 품목', '지능형 안전기술', '후방 교차 충돌방지 보조', '후진 출차 시 후방 교차 차량을 감지하여 운전자에게 경고하고 필요 시에는 브레이크 제어를 통해 후방 교차 충돌방지를 보조합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/ai/rcca.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (39, '기본 포함 품목', '안전', '10에어백 시스템(1열 어드밴스드/센', '1열 어드밴스드/센터 사이드, 운전석 무릎,1/2열 사이드, 전복 대응 커튼 에어백으로 탑승자를 보호합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/safe/10airbag.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (40, '기본 포함 품목', '안전', '유아용 시트 고정장치(2열 2개/3열', '영·유아용 시트를 간편하고 안전하게 장착할 수 있는 ISO 규격의 카시트를 고정할 수 있는 장치를 2열에 2개, 3열에 1개 총 3개를 적용하여 사고 시 카시트에 탑승한 유아를 보호합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/safe/isofix.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (41, '기본 포함 품목', '안전', '구동선회 제어기능', '커브구간에서 선회 가속시 구동력과 제동력을 제어해 언더스티어 현상을 억제하고 차량의 주행 민첩성과 주행 안정성을 향상시키는 토크벡터링 (Torque Vectoring) 시스템입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/safe/atcc.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (42, '기본 포함 품목', '안전', '다중 충돌방지 자동 제동 시스템', '차량의 정면 또는 측면 충돌사고로 에어백 전개 시 차량에 적절한 자동 긴급 제동을 통해 2차 사고 및 다중 충돌을 경감시켜줍니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/safe/mcbs.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (43, '기본 포함 품목', '외관', '다크 크롬 라디에이터 그릴', null, null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/darkchromegrill.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (44, '기본 포함 품목', '외관', 'LED 주간주행등', '주간주행등(DRL)은 낮시간에도 자동으로 켜져 다른 사람들이 차량을 쉽게 볼 수 있도록 합니다. 특히 해질 무렵이나 해뜨기 직전에 차량의 접근을 쉽게 인식하도록 합니다. 차량 시동 후에 자동으로 켜집니다.
※ 광원의 종류
- 벌브 : 유리구 안에 있는 필라멘트에 전류를 흘려 빛을 내는 광원입니다.
- LED : 빛을 내는 반도체 소자로 밝은 빛을 내며 효율이 좋은 광원입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/leddrl.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (45, '기본 포함 품목', '외관', 'LED 포지셔닝 램프', '안개, 야간과 같이 시야확보가 어려울 경우, 차의 존재 및 차폭을 인지할 수 있도록 하는 역할을 합니다.
※ 광원의 종류
- 벌브 : 유리구 안에 있는 필라멘트에 전류를 흘려 빛을 내는 광원입니다.
- LED : 빛을 내는 반도체 소자로 밝은 빛을 내며 효율이 좋은 광원입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/ledpositioninglamp.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (46, '기본 포함 품목', '외관', 'LED 방향지시등', '차량의 진행 방향을 주변 주행 차량 및 보행자에게 알리는 등화장치입니다.
※ 광원의 종류
- 벌브 : 유리구 안에 있는 필라멘트에 전류를 흘려 빛을 내는 광원입니다.
- LED : 빛을 내는 반도체 소자로 밝은 빛을 내며 효율이 좋은 광원입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/ledsignallight.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (47, '기본 포함 품목', '외관', 'Full LED 헤드램프(프로젝션 타', '야간 운전시 전방에 빛을 비춰 운전자의 시야를 확보할 수 있도록 돕습니다.
※ 광원의 종류
- 벌브 : 유리구 안에 있는 필라멘트에 전류를 흘려 빛을 내는 광원입니다.
- LED : 빛을 내는 반도체 소자로 밝은 빛을 내며 효율이 좋은 광원입니다.
* Full LED 타입 : 상향등과 하향등이 모두 LED가 적용되어 광도가 우수하고 고급스러운 이미지를 연출합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/fullheadlamp.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (48, '기본 포함 품목', '외관', '아웃사이드 미러(열선, 전동접이, 전', '주행 중 후측방을 확인할 수 있도록 차량 좌우측에 부착된 거울입니다.
방향지시등 : 차량의 진행방향을 주변 주행 차량 및 보행자에게 알리는 램프를 아웃사이드 미러에 적용했습니다.
열선 기능 : 아웃사이드 미러에 낀 습기를 제거하기 위한 기능입니다.
전동 접이 기능 : 버튼 조작으로 아웃사이드 미러를 접고 펼 수 있는 기능입니다. 리모컨 키로 도어를 여닫을 때 자동으로 접고 펼 수도 있습니다.
전동 조절 기능 : 버튼 조작으로 아웃사이드 미러의 화각을 조', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/outsidemirror.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (49, '기본 포함 품목', '외관', '이중접합 차음유리(윈드실드, 1/2열', '두 겹의 유리로 이루어진 전방 유리의 사이에 소음을 흡수하는 전용 차음필름을 삽입하여 엔진 투과음 및 외부 소음이 실내에 유입되는 것을 감소시켜 탑승자의 운전 쾌적성을 향상시킵니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/laminatedwindow.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (50, '기본 포함 품목', '외관', '도어 포켓 라이팅(1열)', '스마트 키를 소지하고 차량에 접근하거나 리모컨 키를 이용하여 차량 도어를 오픈 할 때 아웃사이드 도어핸들 안쪽에 불빛을 비춰 야간에 차량의 문을 쉽게 열 수 있도록 배려한 편의 기능입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/doorpocketlighting.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (51, '기본 포함 품목', '외관', '싱글 트윈팁 머플러', '차량 후면부 하단에 부착되는 배기장치로 차량 후면부와 조화감 있는 이미지로 디자인의 완성도를 높여줍니다. 머플러 부착방식에 따라 명칭이 상이합니다.
싱글 타입 : 1개의 머플러로 구성
트윈 타입 : 한쪽에 2개의 머플러로 구성
듀얼 타입 : 차량 후면부 좌우에 2개의 머플러가 장착됨', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/singlemuffler.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (52, '기본 포함 품목', '외관', 'LED 리어콤비램프', '헤드램프와 통일감 있는 콤비램프 디자인을 적용하였으며 보석 느낌의 인너렌즈를 적용하여 고급스러운 감성품질을 제공합니다.
※ 광원의 종류
- 벌브 : 유리구 안에 있는 필라멘트에 전류를 흘려 빛을 내는 광원입니다.
- LED : 빛을 내는 반도체 소자로 밝은 빛을 내며 효율이 좋은 광원입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/ledpositioninglamp.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (53, '기본 포함 품목', '외관', 'LED 보조제동등', '기본으로 제공하는 제동등과 별도로 장착되어 브레이크 작동 시 후방 주행 차량에게 제동을 알려 후방 추돌 상황을 방지하는 등화장치입니다.
※ 광원의 종류
- 벌브 : 유리구 안에 있는 필라멘트에 전류를 흘려 빛을 내는 광원입니다.
- LED : 빛을 내는 반도체 소자로 밝은 빛을 내며 효율이 좋은 광원입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/ledstoplamp.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (54, '기본 포함 품목', '외관', '후진가이드램프', '후진 시 점선 패턴의 가이드 조명 구현을 통해 주변 차량 및 보행자에게 후진 의도를 효과적으로 전달하여 사고를 예방합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/rearguidelamp.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (55, '기본 포함 품목', '외관', '리어 스포일러', '주행 시 차량 후면에 발생하는 공기의 와류 현상을 없애주는 장치로 차량의 공력 성능을 향상시킵니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/rearspoiler.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (56, '기본 포함 품목', '외관', '크롬 DLO 몰딩', '차량 도어의 몰딩 부분 소재를 크롬으로 적용하여 고급스러운 감성을 전달합니다.
차량마다 적용부위의 차이가 있습니다.
- 벨트라인 : 차량의 측면 윈도우의 하단을 감싸는 몰딩 부분
- DLO(Day-light opening) : 차량의 측면 윈도우를 감싸는 몰딩 부분', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/dlomolding.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (57, '기본 포함 품목', '외관', '루프랙', '차량 위에 짐을 실을 수 있도록 돕는 장치로 화물적재를 위한 보조기구 장착 시 차량 상태 및 안전을 고려하여 장착해야합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/roofrack.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (58, '기본 포함 품목', '외관', '메탈페인트 스키드 플레이트', '-', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/metalpaintplate_s.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (59, '기본 포함 품목', '외관', '20인치 알로이 휠&타이어', '-', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/20alloywheel_s.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (60, '기본 포함 품목', '외관', '발수 도어(1열)', '빗물 맺힘이나 서리, 성에 등을 막아주는 발수 적용 유리를 앞도어에 장착하여 운전자의 시계를 확보합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/external/frontdoorwindow_s.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (61, '기본 포함 품목', '내장', '베젤리스 인사이드 미러', '-', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/internal/insidemirror.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (62, '기본 포함 품목', '내장', 'LED 실내등(맵램프, 룸램프, 선바', '차량 실내 전체를 비춰주는 룸램프를 LED로 적용하여 어두운 곳에서의 시인성을 향상시킵니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/internal/ledlamp.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (63, '기본 포함 품목', '내장', '가죽 스티어링 휠(열선 포함)', '시동 스위치가 「ON」 또는 엔진이 작동 중일때 스티어링 휠 히터 버튼을 누르면 표시등이 켜지면서 스티어링 휠이 따뜻해집니다. 스티어링 휠 히터 버튼을 누른 후 작동 조건에서 약 30분이 지나면 자동으로 작동을 멈춥니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/internal/leathersteeringwheel.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (64, '기본 포함 품목', '내장', '클러스터(12.3인치 컬러 LCD)', '컬러 LCD 클러스터(1,920x720)는 시인성이 높고 정보 파악이 용이하며, 주행모드별 차별화된 그래픽으로 즐거운 드라이빙 환경을 제공합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/internal/12.3cluster.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (65, '기본 포함 품목', '내장', '인조가죽 감싸기', '-', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/internal/leatherwrapping.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (66, '기본 포함 품목', '내장', '도어 암레스트 리얼 스티치', '-', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/internal/doorarmrest.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (67, '기본 포함 품목', '시트', '1열 열선/통풍 시트', '시동이 걸린 상태에서 해당 좌석 히터 스위치를 누르면 강약조절 표시등이 켜져 사용 중임을 나타내고 해당 좌석이 따뜻해지는 열선기능과 시동이 걸린 상태에서 해당 좌석의 통풍 스위치를 누르면 표시등이 켜지면서 해당 좌석에 바람이 나오는 통풍기능이 적용되었습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/sheet/frontheated.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (68, '기본 포함 품목', '시트', '2열 열선시트', '3단계로 온도 조절이 가능한 열선시트를 적용하여 쾌적한 승차감을 제공합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/sheet/2_heated.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (69, '기본 포함 품목', '시트', '2열 폴드 & 다이브/슬라이딩 & 리', '평면형태의 2열 공간을 제공하는 풀플랫 폴딩 2열시트로 차원이 다른 공간/거주성을 확보해 넉넉한 러기지 공간은 물론 프라이빗 스페이스로 활용할 수 있습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/sheet/fold_dive.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (70, '기본 포함 품목', '시트', '3열 6:4분할 폴딩/리클라이닝 시트', '3열 시트 및 러기지 사이드에 적용된 전자식 스위치로 시트를 폴딩 및 리클라이닝하여 화물 적재 시 편리합니다. 또한 좌석 등받이 부분을 후방으로 눕힐 수 있는 리클라이닝 기능을 적용하여 성인 탑승 및 장거리 이동 시 거주 편의성을 높였습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/sheet/64folding.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (71, '기본 포함 품목', '시트', '퀼팅 천연가죽 시트(블랙/쿨그레이)', '팰리세이드는 옵션에 따라 인조가죽, 가죽, 나파가죽, 퀼팅 나파가죽 시트를 선택할 수 있습니다.
- 인조가죽 시트 : 합성섬유를 이용하여 가죽의 질감을 구현한 인조가죽으로 제작된 시트입니다.
- 가죽 시트 : 실제 가죽으로 제작되어 편안하며 고급스러운 착좌감을 제공합니다.
- 나파가죽 시트 : 가죽 표면을 코팅처리하여 가죽의 내구성은 높이면서도 부드러운 감촉을 선사하는 시트입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/sheet/realleather.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (72, '기본 포함 품목', '시트', '운전석 전동시트(10way, 4way', '운전석의 시트 포지션을 조정하여 운전자의 체형에 맞는 편안한 자세를 유지할 수 있도록 돕는 기능입니다.
- 10way 전동시트 : 운전석 좌하단에 위치한 조작부로 8방향으로 조절 기능(시트백 기울기, 시트 앞/뒤 이동, 쿠션부 앞/뒤 높이 조절)과 허리 지지대 조절 기능을 전동 방식으로 조절합니다.
- 4way 럼버서포트 : 허리 지지대 조절 기능을 4 방향으로 조절합니다.
- 쿠션 익스텐션 : 운전자의 허벅지 길이에 맞게 시트 하단부를 조절하는 쿠션 ', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/sheet/10_driverseat.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (73, '기본 포함 품목', '시트', '동승석 전동시트(8way, 워크인 디', '동승석의 시트 포지션을 조정하여 동승자의 체형에 맞는 편안한 자세를 유지할 수 있도록 돕는 기능입니다. 8방향(시트백 기울기, 시트 앞/뒤 이동, 쿠션부 앞/뒤 높이 조절)으로 조절이 기능하고 운전자 및 뒷좌석(2열) 승객이 동승석 시트 위치를 조절할 수 있는 워크인 디바이스를 적용하여 실내 공간 활용 편의성을 높였습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/sheet/10_passengerseat.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (74, '기본 포함 품목', '편의', '버튼시동 & 스마트키', '일반 키와는 달리 휴대만으로 도어(트렁크 포함)를 잠그거나 열고, 엔진 시동을 걸 수 있는 장치입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/smartkey.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (75, '기본 포함 품목', '편의', '전동식 파킹 브레이크(오토홀드 포함)', '버튼 조작만으로 파킹 브레이크 작동 또는 해제가 가능하며, 정차 시 자동으로 제동상태를 유지하는 오토 홀드 기능 적용으로 편의성을 높였습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/epb.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (76, '기본 포함 품목', '편의', '패들 쉬프트', '운전 중 간단한 조작만으로도 스포티한 수동 변속모드를 지원합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/paddleshift.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (77, '기본 포함 품목', '편의', '3존 독립제어 풀오토 에어컨 (공기청', '원하는 온도를 설정하면 자동으로 설정된 온도로 풍량을 조절하여 쾌적한 실내를 완성합니다.
공기 청정 모드 : 일정 시간 동안 외부 공기를 차단하고 내부 순환모드를 가동하여 실내에서 순환하는 공기를 반복적으로 필터링하여 공기질을 개선시키는 기능입니다.
3존 독립제어 : 운전석이나 동승석 뿐만 아니라 후석에서도 개별 제어가 가능한 에어컨입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/3_fullautoair.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (78, '기본 포함 품목', '편의', '공기질 센서', '실내 공기질을 실시간으로 확인할 수 있어 공기 청정 모드 사용이나 환기를 유도합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/airsensor.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (79, '기본 포함 품목', '편의', '마이크로 에어 필터', '미세먼지의 실내 유입의 방지하기 위한 에어필터입니다.
글로브 박스 뒤쪽에 장착되어 바깥에서 공기 조화 장치를 통하여 차 안으로 들어오는 먼지나 꽃가루 등을 걸러줍니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/airfilter.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (80, '기본 포함 품목', '편의', '자외선 차단 유리(윈드실드)', '차량 전방 유리에 자외선을 차단 기능을 적용하여 탑승객은 물론 차량 실내 내장재를 보호합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/uvprotectglass.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (81, '기본 포함 품목', '편의', '오토 디포그', '전면유리의 김서림을 감지해 스스로 전면 유리 및 앞좌석 유리의 김서림을 없애 운전시야를 확보합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/autodefog.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (82, '기본 포함 품목', '편의', '레인센서', '스티어링 휠 우측 레버의 와이퍼 조절장치 스위치를 AUTO로 위치하였을 때 주행 중 우천상황을 자동으로 감지하여 와이퍼가 작동 및 조작단계를 자동으로 조절하는 기능입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/rainsensor.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (83, '기본 포함 품목', '편의', '운전석 공조 연동 자동 제어', '시동 후 공조 설정 온도와 실제 온도의 차이가 많이 나는 경우, 공조기 외 스티어링 휠 열선, 시트 열선/통풍을 자동으로 감지하여 통합 제어하는 기능입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/driver_hvac.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (84, '기본 포함 품목', '편의', 'USB 충전기(1열 1개, 2열 2개', '차량용 충전기로서 USB 포트를 통해 각종 스마트폰 및 태블릿 기기 충전이 가능합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/usbcharger.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (85, '기본 포함 품목', '편의', '파워 아웃렛(1열 1개, 2열 1개,', '시동이 걸린 상태에서 실내에서 전기 제품(예 : 진공청소기, 소형냉장고, 게임기 등)을 사용할 수 있도록 돕습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/poweroutlet.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (86, '기본 포함 품목', '편의', '세이프티 파워 윈도우(1/2열)', '유리창이 원터치 자동 닫힘 기능이 작동하여 닫히는 중에 일정한 힘에 의해 막히면 자동으로 닫힘을 멈추고, 일정한 높이만큼 다시 열리는 기능입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/safetypowerwindow.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (87, '기본 포함 품목', '편의', '후방 모니터', '후진 주차 시 디스플레이 오디오 또는 내비게이션 화면에 후방 상황을 표시하여 편의성을 높였습니다.
조향연동 기능 : 스티어링 휠 조정 시 그에 따른 예상 주행 궤적도 같이 표시하여 편의성을 높였습니다.
DRM(Driving Rear Monitor) 기능 : 주행 중 후방 영상을 실시간으로 확인하여 룸미러 시야 확보가 불가능 할 때, 후방 상황을 인지할 수 있습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/rearmonitor.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (88, '기본 포함 품목', '편의', '확산형 루프 에어 밴트', '벤트 테두리에 홀(HOLE)을 적용하여 바람이 직접 분사가 아닌 간접(확산) 분사될 수 있도록 구현하여 조금 더 쾌적한 환경을 제공합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/roofairvent.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (89, '기본 포함 품목', '편의', '오토 라이트 컨트롤', '대시보드 중앙에 위치한 조도센서를 이용하여 외부 밝기에 따라 헤드램프를 자동으로 조절하는 장치입니다. 스티어링 휠 좌측에 위치한 조명 스위치를 「AUTO」 위치에 두면 작동합니다.
- 대시보드 : 운전석과 조수석 정면에 있으며, 계기판과 센터페시아를 포함합니다.
※ 스마트/VAN 스마트 트림 선택 시, 위 이미지와는 달리 내장 색상이 블랙으로 적용됩니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/autolightcontrol.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (90, '기본 포함 품목', '편의', '스마트키 원격시동', '차량 탑승 전 스마트키를 이용하여 원격으로 시동을 걸 수 있으며, 냉/난방 장치는 시동을 끄기 전 설정된 상태로 작동이 가능합니다.
* 차량 10m 이내에서 도어 잠금 버튼을 누른 후 4초 이내에 원격시동 버튼을 2초 이상 누르면 시동이 걸립니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/smartkeyremote.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (91, '기본 포함 품목', '편의', '전방/후방 주차 거리 경고', '범퍼에 내장된 초음파 센서로 장애물과의 거리를 감지하여 거리별로 차별화된 경고음을 울려 주차 편의성 및 안전성을 제공합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/pdw.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (92, '기본 포함 품목', '편의', '전동식 틸트 & 텔레스코픽 스티어링 ', '조절 스위치를 이용하여 스티어링 휠의 높낮이와 전/후 위치를 조절할 수 있습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/autosteering.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (93, '기본 포함 품목', '편의', '스마트폰 무선충전', '중앙 콘솔에 휴대폰 무선 충전을 위한 시스템이 적용되어 있습니다. 또한 엔진에 시동을 끈 후 충전 패드에 휴대폰이 놓여있는 상태에서 운전석 또는 동승석 도어를 열면 게시판에 \''휴대폰이 무선 충전기에 있습니다\''라는 경고문 및 경고음(음성안내 적용 차량)으로 알려줍니다.
* 무선 충전 시스템은 Qi를 지원하는 휴대폰 한 대를 대상으로 무선충전을 지원하며, Qi를 지원하는 휴대폰은 휴대폰 제조사를 통해 확인 가능합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/wirelesscharging.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (94, '기본 포함 품목', '편의', '스마트 파워 테일게이트', '스위치 및 스마트키 버튼으로 테일게이트 개방이 가능하며, 설정을 통해 개폐 속도 조절 및 열림 높이 조절이 가능합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/powertailgate.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (95, '기본 포함 품목', '편의', '서라운드 뷰 모니터', '차량 앞/뒤/좌/우 360도 모든 상황을 AVN화면을 통해 볼 수 있는 장치로 고화질 카메라 및 디지털 영상 전송 방식을 적용하여 영상 경계선 없이 선명하고 깨끗한 화질을 제공합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/svm.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (96, '기본 포함 품목', '편의', '후측방 모니터', '방향지시등 스위치 조작과 연동해 차로 변경 시 기존 아웃사이드 미러 대비 더 넓은 후측방 영역을 클러스터에 표시하여 안전한 주행을 도와줍니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/convenience/bvm.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (97, '기본 포함 품목', '멀티미디어', '12.3인치 내비게이션(블루링크, 폰', '와이드하고 품격 있는 실내공간을 연출하고 고해상도 대화면으로 뛰어난 시인성과 최첨단 인포테인먼트 기능을 제공합니다.
주요기능 : 대화면 HD급 고해상도(1,920x720) 모니터, 내비게이션 자동 무선 업데이트, 개인화 프로필, 서버형 음성인식 시스템, 블루링크', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/multimedia/12.3navi.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (98, '기본 포함 품목', '멀티미디어', '하이패스', '유료 도로로 진출입시 통행료가 자동결제 되는 장치입니다. 하이패스 시스템은 시동이 걸려있는 상태에서만 작동합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/multimedia/hipass.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (99, '기본 포함 품목', '멀티미디어', '후석 대화모드', '운전자의 음성을 운전석 마이크를 통하여 뒷좌석 동승자와의 대화 편의성을 높였습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/multimedia/reartalking.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (100, '기본 포함 품목', '멀티미디어', '후석 취침모드', '뒷좌석 동승자가 취침 시, 뒷좌석 스피커가 모두 음소거가 되고 운전석 스피커로만 음원이 출력되어, 뒷좌석을 조용한 공간으로 활용할 수 있습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/multimedia/rearsleep.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (101, '기본 포함 품목', '멀티미디어', '일반 오디오 시스템(8스피커, 블루투', '차량 내부 공간의 음향 특성에 맞게 세심하게 조정된 8개의 스피커를 통하여 기본에 충실한 사운드를 감상할 수 있습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/multimedia/audiosystem.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (102, '기본 포함 품목', '멀티미디어', '멀티미디어용 USB단자(1열 1개)', 'MP3, USB 저장 장치 또는 iPod 등 외부 음향 기기(또는 음악/동영상 등 미디어 파일 저장 장치)를 차량에 연결하여 차량 스피커를 통하여 음악을 듣거나 차량 오디오 또는 인포테인먼트 시스템으로 재생할 수 있는 편의 장치 입니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/multimedia/multiusb.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (103, '선택품목', '상세 품목', '컴포트 II - 후석 승객 알림', '[후석 승객 알림]초음파 센서를 통해 뒷좌석에 남아있는 승객의 움직임을 감지하여 운전자에게 경고함으로써 부주의에 의한 유아 또는 반려 동물 등의 방치 사고를 예방하는 신기술입니다.[메탈 리어범퍼스텝]러기지 룸 앞쪽 하단부를 메탈로 만들어 물건을 싣고 내릴 때나 사람이 올라갈 때 차체를 보호해줍니다.[메탈 도어스커프]자동차를 타고 내리는 도어의 문틈 하부를 보호하는 도어스커프 부분을 메탈로 만들어 차체를 보호하고 메탈 디자인으로 고급스러운 감성을 전달합니', 1090000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/roa.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (104, '선택품목', '상세 품목', '컴포트 II - 메탈 리어범퍼스텝', '[메탈 리어범퍼스텝]러기지 룸 앞쪽 하단부를 메탈로 만들어 물건을 싣고 내릴 때나 사람이 올라갈 때 차체를 보호해줍니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/metalrearbumper.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (105, '선택품목', '상세 품목', '컴포트 II - 메탈 도어스커프', '[메탈 도어스커프]자동차를 타고 내리는 도어의 문틈 하부를 보호하는 도어스커프 부분을 메탈로 만들어 차체를 보호하고 메탈 디자인으로 고급스러운 감성을 전달합니다.

', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/metaldoorscuff.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (106, '선택품목', '상세 품목', '컴포트 II - 3열 파워폴딩시트', '[3열 파워폴딩시트]러기지 사이드에 있는 버튼으로 3열 시트를 접었다 펼 수 있으며, 2열 시트도 조작할 수 있어 화물 적재시나 3열 이용시 사용자의 편의성을 높였습니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/powerfolding.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (107, '선택품목', '상세 품목', '컴포트 II - 3열 열선시트', '[3열 열선시트]시동이 걸린 상태에서 해당 좌석 히터 스위치를 누르면 강약조절 표시등이 켜져 사용 중임을 나타내고 해당 좌석이 따뜻해집니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/3_heated.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (108, '선택품목', '상세 품목', '컴포트 II - 헤드업 디스플레이', '[헤드업 디스플레이]주요 주행 정보를 전면 윈드실드에 표시하며, 밝기가 최적화되어 주간에도 시인성이 뛰어납니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/headupdisplay.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (109, '선택품목', '상세 품목', '주차보조 시스템 II - 후방 주차 ', '[후방 주차 충돌방지 보조]주차 또는 출차 시 저속 후진 중 후방카메라와 센서로 정후면에 위치한 보행자 및 장애물과의 충돌이 예상되면 운전자에게 경고하고 차량의 제동을 제어하여 충돌방지를 보조합니다.[원격 스마트 주차 보조]주차 보조 기능을 활성화 한 후 주차공간을 발견하게 되면 차량 내 안내에 따라 하차한 다음, 스마트키의 작동 버튼을 누르고만 있으면 차가 스스로 주차합니다. 직각주차 및 평행주차 모두 가능하며, 운전자 탑승 시에도 차량 내부의 작동 ', 690000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/pca.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (110, '선택품목', '상세 품목', '주차보조 시스템 II - 원격 스마트', '[원격 스마트 주차 보조]주차 보조 기능을 활성화 한 후 주차공간을 발견하게 되면 차량 내 안내에 따라 하차한 다음, 스마트키의 작동 버튼을 누르고만 있으면 차가 스스로 주차합니다. 직각주차 및 평행주차 모두 가능하며, 운전자 탑승 시에도 차량 내부의 작동 버튼을 누르고 있으면 자동 주차 보조를 지원합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/rspa.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (111, '선택품목', '상세 품목', '2열 통풍 시트', '시동이 걸린 상태에서 해당 좌석의 통풍 스위치를 누르면 표시등이 켜지면서 해당 좌석에 바람이 나오는 편의장치입니다.', 400000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/2_cooling.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (112, '선택품목', '상세 품목', '듀얼 와이드 선루프', '후석에 고정 글라스를 적용한 듀얼 파노라믹 선루프로 2/3열의 탑승객에게도 넓은 개방감을 선사합니다.', 890000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/sun_roof.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (113, '선택품목', '상세 품목', '빌트인 캠(보조배터리 포함)', '빌트인 적용된 영상기록장치로, 내비게이션 화면을 통해 영상 확인 및 앱 연동을 통해 영상 확인 및 SNS 공유가 가능합니다.', 690000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/cam.jpg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (114, '선택품목', '상세 품목', '현대스마트센스 I - 전방 추돌방지 ', '[전방 충돌방지 보조(교차 차량/추월시 대향차/측방 접근차)]선행 차량이 갑자기 속도를 줄이거나, 앞에 정지 차량 혹은 보행자가 나타나는 등 전방 충돌 위험이 감지되면 경고를 해줍니다. 경고 후에도 충돌 위험이 높아지면 자동으로 제동을 도와줍니다. 주행 중 전방의 자전거 탑승자 및 교차로에서 좌회전 시 맞은편에서 다가오는 차량과 충돌 위험이 있다면 자동으로 제동을 도와줍니다.[내비게이션 기반 스마트 크루즈 컨트롤(진출입로)]스마트 크루즈 작동 중 고속도', 790000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/smart_front_collision.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (115, '선택품목', '상세 품목', '현대스마트센스 I - 내비게이션 기반', '스마트 크루즈 작동 중 고속도로/도시고속도로/자동차전용 도로 내 고속도로 진출입로 주행 시 차로를 판단하여 사전감속 또는 최적 속도에 맞추어 감속을 진행합니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/smar_ncss.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (116, '선택품목', '상세 품목', '현대스마트센스 I - 고속도로 주행 ', '[고속도로 주행 보조 2] 고속도로 / 자동차 전용도로에서 앞차와의 거리와 설정 속도를 유지하며 주행할 뿐 아니라, 곡선로에서도 차로의 중앙을 유지하며 주행할 수 있도록 도와줍니다. 일정 속도 이상으로 주행 시, 스티어링 휠을 잡은 상태에서 방향지시등 스위치를 변경하고자 하는 차로 방향으로 움직이면 자동으로 차로를 변경해 줍니다.', null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/selected/smart_highway.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (117, '선택품목', 'H Genuine Accessorie', '듀얼 머플러 패키지', '[내비게이션 기반 스마트 크루즈 컨트롤(진출입로)]차량 후면부에 스포티함을 한층 강화시켜주는 듀얼 머플러와 디자인 리어 스키드 상품입니다.
1) 듀얼 머플러 & 리어 스키드 (캘리그래피 트림)
2) 듀얼 머플러 & 리어 스키드 (일반 트림)', 840000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/H_Genuine_Accessories/dualmufflerpackage.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (118, '선택품목', 'H Genuine Accessorie', '빌트인 공기청정기', 'H13 등급 및 활성탄+제올라이트 복합소재 필터를 적용하여 초미세먼지뿐 아니라 실내 유해가스(VOCs) 정화 기능이 우수한 상품입니다.
* 동승석 적용                                              ※ 빌트인 공기청정기 전용 에어필터의 권장 사용기간은 6개월이며(하루 2시간 사용 기준), 에어필터는 현대 Shop(Shop.Hyundai.com) 현대브랜드관을 통해 개별 품목 단위로 구매 가능합니다.', 400000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/H_Genuine_Accessories/builtinaircleaner.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (119, '선택품목', 'H Genuine Accessorie', '사이드스텝', '뛰어난 일체감을 통해 사이드 디자인을 개선시켜 주며, 미끄럼 방지 패턴이 적용되어 어린이 및 노약자의 승하차 시 안정성을 높여주는 상품입니다.', 350000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/H_Genuine_Accessories/sidestep.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (120, '선택품목', 'H Genuine Accessorie', '적외선 무릎워머', '스티어링 컬럼 하단에 설치된 복사 열선이 운전자의 허벅지와 무릎에 복사열을 전달하여 저온에서 히터 바람 없이도 냉감을 줄여 보다 쾌적한 환경을 제공해주는 상품입니다.', 300000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/H_Genuine_Accessories/kneewarmer.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (121, '선택품목', 'H Genuine Accessorie', '차량 보호 필름', '카 라이프중 손상되기 쉬운 프론트/리어 범프등 7부위에 우레탄 계열의 투명한 보호 필름을 부착하여 스톤칩으로 인한 페인트 손상 및 생활 스크래치를 예방하여 깨끗한 바디를 유지하는데 도움을 줍니다.
- 적용부위: 프론트 범퍼 사이드, 도어컵, 도어 엣지, 도어 스텝, 주유구 도어, 리어 범퍼 사이드, 사이드 미러', 490000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/H_Genuine_Accessories/carprotector.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (122, '선택품목', 'H Genuine Accessorie', '프로텍션 매트 패키지 I - 러기지 ', '차량 설계 데이터를 반영한 3D 형상 디자인으로 차량에 딱 맞는 완벽한 일체감과 실내 고급감을 제공합니다.
방오/방수 효과로 매트 오염시 세척/건조가 탁월합니다.

[프로텍션 매트 패키지]
- 구성품목 : 프론트 플로어 매트 2개(좌/우), 리어 플로어 매트, 러기지 매트', 250000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/H_Genuine_Accessories/luggageprotectmat.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (123, '선택품목', 'H Genuine Accessorie', '프로텍션 매트 패키지 I - 플로어매', null, null, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/H_Genuine_Accessories/floormat.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (124, '선택품목', 'N performance', '20인치 다크 스퍼터링 휠', '스포티한 디자인 감성을 원하는 고객을 위한 N 퍼포먼스 파츠 휠입니다.

* 단품 선택만 가능하며, 알콘 브레이크와 동시 선택은 불가', 840000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/N_performance/20_darkwheel.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (125, '선택품목', 'N performance', '20인치 블랙톤 전면 가공 휠', '알콘 브레이크 시스템 장착을 위한 전용휠이며 다이아몬트 커팅 피니쉬로 플래그십 SUV에 어울리는 고급스러운 디자인 감성을 제공합니다.

[알콘 (alcon) 단조 브레이크 & 20인치 휠 패키지]
알콘사와 협업 개발한 브레이크 시스템은 보다 강건한 재질의 캘리퍼와 더욱 커진 디스크 사이즈로 보다 안정적인 제동성능을 제공합니다.

- 구성품목 : 20인치 블랙톤 전면 가공 휠, 알콘 (alcon) 단조 6피스톤 캘리퍼, 볼팅타입 하이브리드 대용량 디스크,', 840000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/N_performance/20inchwheel.jpeg', null);
INSERT INTO CAR_OPTION (car_option_id, category, category_detail, option_name, option_detail, price, photo_url, parent_option_id) VALUES (126, '선택품목', 'N performance', '알콘(alcon) 단조 브레이크 & ', '6피스톤 단조 캘리퍼 : 단조 소재를 적용하여 강성을 증대하였으며(기존: 주조) 피스톤 직경 증대로 제동 응답성이 향상되었습니다.
-대용량 하이브리드 디스크 : 하이브리드 기술이 들어간 볼팅타입 디스크의 용량을 더욱 증대하여 경량화외에 열용량 증대로 인해 제동 응답성이 향상되었습니다. (디스크 사이즈: 380mm)
로우 스틸패드 : 마찰계수 증대로 제동성이 향상되었습니다.

[알콘 (alcon) 단조 브레이크 & 20인치 휠 패키지]
알콘사와 협업 개발', 3660000, 'https://topcariving.s3.ap-northeast-2.amazonaws.com/N_performance/alconbreak.jpeg', null)