springdoc:
  packages-to-scan: com.backend.topcariving.domain
  swagger-ui:
    path: /swagger
    disable-swagger-default-url: true
    display-request-duration: true
    operations-sorter: alpha

spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
    path: /h2-console

  sql:
    init:
      mode: always
      schema-locations: classpath*:initDb/schema.sql
      data-locations: classpath*:initDb/data.sql